runtime: php55
api_version: 1
skip_files:
  sass/
  mockups/
  README.md
  ^node_modules/(?!jquery/dist/).*

handlers:
# TODO: be more specific about files that we upload?
# Serve images as static resources.
#- url: /(imgs|styles|js)/(.+\.(gif|png|jpg|jpeg|css|js|html))$
#  static_files: \1/\2
#  upload: (imgs|styles|js)/.+\.(gif|png|jpg|jpeg|css|js|html)$

# easy way is to just upload all the static directories
- url: /js
  static_dir: js
- url: /styles
  static_dir: styles
- url: /imgs
  static_dir: imgs
- url: /media
  static_dir: media
- url: /node_modules/jquery/dist
  static_dir: node_modules/jquery/dist
- url: /bower_components
  static_dir: bower_components

  # application_readable: true
- url: /
  script: index.php

# Serve php scripts.
- url: /(.*\.php)$
  script: \1